// GENERATED FILE - do not edit by hand.
// Source: packages/protocol/fixtures/**/*.json
// Regenerate with: pnpm --filter @agent-voice/protocol generate:fixtures

export const events = {
  'action.failed': {
    v: 1,
    id: 'evt_0012',
    ts: '2026-01-01T12:00:14.000Z',
    conversationId: 'conv_demo',
    type: 'action.failed',
    actionId: 'act_01',
    code: 'unavailable',
    summary: 'The agent is not reachable right now, so nothing was changed.',
    retryable: true,
  },
  'action.progress': {
    v: 1,
    id: 'evt_0007',
    ts: '2026-01-01T12:00:05.000Z',
    conversationId: 'conv_demo',
    type: 'action.progress',
    actionId: 'act_01',
    message: 'Fetching the last nightly run',
    percent: 40,
  },
  'action.started': {
    v: 1,
    id: 'evt_0006',
    ts: '2026-01-01T12:00:03.200Z',
    conversationId: 'conv_demo',
    type: 'action.started',
    actionId: 'act_01',
    title: 'Check the nightly build and summarize failures',
    adapter: 'openai-http',
  },
  'action.verified': {
    v: 1,
    id: 'evt_0011',
    ts: '2026-01-01T12:00:14.000Z',
    conversationId: 'conv_demo',
    type: 'action.verified',
    actionId: 'act_01',
    summary:
      'The nightly build failed on two jobs: the integration suite timed out and the docs build had a broken link. Both jobs were re-run.',
    verification: {
      state: 'verified',
      method: 'agent:tool-check',
      detail: 'Delegated agent checked the resulting pipeline state',
    },
    artifacts: [
      {
        id: 'art_02',
        kind: 'text',
        title: 'Failure summary',
        text: 'integration-suite: timeout after 20m\ndocs-build: broken link in docs/api.md',
      },
    ],
  },
  'agent.message.final': {
    v: 1,
    id: 'evt_0005',
    ts: '2026-01-01T12:00:03.000Z',
    conversationId: 'conv_demo',
    type: 'agent.message.final',
    messageId: 'msg_agent_01',
    text: 'Sure, let me ask the agent to look at the nightly build.',
  },
  'agent.message.partial': {
    v: 1,
    id: 'evt_0004',
    ts: '2026-01-01T12:00:02.500Z',
    conversationId: 'conv_demo',
    type: 'agent.message.partial',
    messageId: 'msg_agent_01',
    text: 'Sure, let me ask the agent',
  },
  'approval.requested': {
    v: 1,
    id: 'evt_0008',
    ts: '2026-01-01T12:00:06.000Z',
    conversationId: 'conv_demo',
    type: 'approval.requested',
    actionId: 'act_01',
    approvalId: 'apr_01',
    prompt: 'Re-run the two failed jobs on the nightly pipeline?',
    expiresAt: '2026-01-01T12:02:06.000Z',
  },
  'approval.resolved': {
    v: 1,
    id: 'evt_0009',
    ts: '2026-01-01T12:00:10.000Z',
    conversationId: 'conv_demo',
    type: 'approval.resolved',
    actionId: 'act_01',
    approvalId: 'apr_01',
    decision: 'approved',
    resolvedBy: 'user',
  },
  'artifact.created': {
    v: 1,
    id: 'evt_0010',
    ts: '2026-01-01T12:00:12.000Z',
    conversationId: 'conv_demo',
    type: 'artifact.created',
    actionId: 'act_01',
    artifact: {
      id: 'art_01',
      kind: 'link',
      title: 'Nightly pipeline run #4812',
      url: 'https://ci.example.com/pipelines/4812',
    },
  },
  'conversation.cancelled': {
    v: 1,
    id: 'evt_0013',
    ts: '2026-01-01T12:05:00.000Z',
    conversationId: 'conv_demo',
    type: 'conversation.cancelled',
    reason: 'user',
  },
  'conversation.started': {
    v: 1,
    id: 'evt_0001',
    ts: '2026-01-01T12:00:00.000Z',
    conversationId: 'conv_demo',
    type: 'conversation.started',
    agentName: 'agent-voice',
    adapter: 'openai-http',
  },
  'user.transcript.final': {
    v: 1,
    id: 'evt_0003',
    ts: '2026-01-01T12:00:02.000Z',
    conversationId: 'conv_demo',
    type: 'user.transcript.final',
    segmentId: 'seg_user_01',
    text: 'Can you check whether the nightly build passed and summarize the failures?',
  },
  'user.transcript.partial': {
    v: 1,
    id: 'evt_0002',
    ts: '2026-01-01T12:00:01.000Z',
    conversationId: 'conv_demo',
    type: 'user.transcript.partial',
    segmentId: 'seg_user_01',
    text: 'Can you check whether the nightly',
  },
} as const;

export const commands = {
  'action.cancel': {
    v: 1,
    id: 'cmd_0002',
    ts: '2026-01-01T12:00:09.000Z',
    conversationId: 'conv_demo',
    type: 'action.cancel',
    actionId: 'act_01',
  },
  'approval.respond': {
    v: 1,
    id: 'cmd_0001',
    ts: '2026-01-01T12:00:09.000Z',
    conversationId: 'conv_demo',
    type: 'approval.respond',
    actionId: 'act_01',
    approvalId: 'apr_01',
    decision: 'approved',
  },
  'conversation.cancel': {
    v: 1,
    id: 'cmd_0003',
    ts: '2026-01-01T12:04:59.000Z',
    conversationId: 'conv_demo',
    type: 'conversation.cancel',
  },
} as const;

export const invalid = {
  'approval-resolved-bad-decision': {
    expect: 'invalid_event',
    message: {
      v: 1,
      id: 'evt_bad_06',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'approval.resolved',
      actionId: 'act_01',
      approvalId: 'apr_01',
      decision: 'maybe',
    },
  },
  'approval-without-action': {
    expect: 'invalid_event',
    note: 'blanket approvals (no actionId) are not representable',
    message: {
      v: 1,
      id: 'evt_bad_05',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'approval.requested',
      approvalId: 'apr_01',
      prompt: 'Approve everything for this session?',
      expiresAt: '2026-01-01T12:02:00.000Z',
    },
  },
  'approval-without-expiry': {
    expect: 'invalid_event',
    note: 'every approval is bound to an action and must expire',
    message: {
      v: 1,
      id: 'evt_bad_04',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'approval.requested',
      actionId: 'act_01',
      approvalId: 'apr_01',
      prompt: 'Proceed?',
    },
  },
  'artifact-javascript-url': {
    expect: 'invalid_event',
    note: 'artifact URLs must be http(s); script and data URLs are rejected',
    message: {
      v: 1,
      id: 'evt_bad_01',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'artifact.created',
      actionId: 'act_01',
      artifact: {
        id: 'art_x',
        kind: 'link',
        title: 'Click',
        url: 'javascript:alert(1)',
      },
    },
  },
  'artifact-link-without-url': {
    expect: 'invalid_event',
    note: 'link artifacts require a url; text artifacts require text',
    message: {
      v: 1,
      id: 'evt_bad_03',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'artifact.created',
      actionId: 'act_01',
      artifact: {
        id: 'art_x',
        kind: 'link',
        title: 'Run',
      },
    },
  },
  'artifact-url-with-credentials': {
    expect: 'invalid_event',
    note: 'artifact URLs must not embed userinfo',
    message: {
      v: 1,
      id: 'evt_bad_02',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'artifact.created',
      actionId: 'act_01',
      artifact: {
        id: 'art_x',
        kind: 'link',
        title: 'Run',
        url: 'https://user:pw@ci.example.com/run/1',
      },
    },
  },
  'extra-field': {
    expect: 'invalid_event',
    note: 'events are strict; unknown keys are rejected',
    message: {
      v: 1,
      id: 'evt_bad_13',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'conversation.cancelled',
      reason: 'user',
      extra: true,
    },
  },
  'failed-unknown-code': {
    expect: 'invalid_event',
    message: {
      v: 1,
      id: 'evt_bad_09',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'action.failed',
      actionId: 'act_01',
      code: 'exploded',
      summary: 'Something went wrong.',
      retryable: false,
    },
  },
  'progress-percent-out-of-range': {
    expect: 'invalid_event',
    message: {
      v: 1,
      id: 'evt_bad_07',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'action.progress',
      actionId: 'act_01',
      message: 'Working',
      percent: 140,
    },
  },
  'too-many-artifacts': {
    expect: 'invalid_event',
    message: {
      v: 1,
      id: 'evt_bad_14',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'action.verified',
      actionId: 'act_01',
      summary: 'Done.',
      verification: {
        state: 'verified',
        method: 'test',
      },
      artifacts: [
        {
          id: 'art_0',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_1',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_2',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_3',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_4',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_5',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_6',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_7',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_8',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_9',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_10',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_11',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_12',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_13',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_14',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_15',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_16',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_17',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_18',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_19',
          kind: 'text',
          title: 't',
          text: 'x',
        },
        {
          id: 'art_20',
          kind: 'text',
          title: 't',
          text: 'x',
        },
      ],
    },
  },
  'transcript-too-long': {
    expect: 'invalid_event',
    note: 'text is bounded even when the whole message fits the byte budget',
    message: {
      v: 1,
      id: 'evt_bad_10',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'user.transcript.final',
      segmentId: 'seg_01',
      text: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    },
  },
  'unknown-type': {
    expect: 'unknown_event',
    message: {
      v: 1,
      id: 'evt_bad_11',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'agent.thought.partial',
      text: '...',
    },
  },
  'unsupported-version': {
    expect: 'unsupported_version',
    message: {
      v: 2,
      id: 'evt_bad_12',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'conversation.started',
      agentName: 'agent-voice',
      adapter: 'openai-http',
    },
  },
  'verified-with-unverified-state': {
    expect: 'invalid_event',
    note: 'action.verified can only carry a verified verification state',
    message: {
      v: 1,
      id: 'evt_bad_08',
      ts: '2026-01-01T12:00:00.000Z',
      conversationId: 'conv_demo',
      type: 'action.verified',
      actionId: 'act_01',
      summary: 'Done, probably.',
      verification: {
        state: 'unverified',
        method: 'guess',
      },
    },
  },
} as const;

export const scenarios = {
  cancellation: {
    name: 'cancellation',
    description:
      'The user cancels a running action; the approval expires unanswered and the conversation is cancelled.',
    events: [
      {
        v: 1,
        id: 'evt_c_001',
        ts: '2026-01-01T14:00:00.000Z',
        conversationId: 'conv_cancel',
        type: 'conversation.started',
        agentName: 'agent-voice',
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_c_002',
        ts: '2026-01-01T14:00:02.000Z',
        conversationId: 'conv_cancel',
        type: 'user.transcript.final',
        segmentId: 'seg_u_1',
        text: 'Rotate the staging database credentials.',
      },
      {
        v: 1,
        id: 'evt_c_003',
        ts: '2026-01-01T14:00:02.500Z',
        conversationId: 'conv_cancel',
        type: 'action.started',
        actionId: 'act_c_1',
        title: 'Rotate staging database credentials',
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_c_004',
        ts: '2026-01-01T14:00:03.000Z',
        conversationId: 'conv_cancel',
        type: 'approval.requested',
        actionId: 'act_c_1',
        approvalId: 'apr_c_1',
        prompt:
          'Rotate the staging database credentials now? Connected services will need the new values.',
        expiresAt: '2026-01-01T14:02:03.000Z',
      },
      {
        v: 1,
        id: 'evt_c_005',
        ts: '2026-01-01T14:00:20.000Z',
        conversationId: 'conv_cancel',
        type: 'approval.resolved',
        actionId: 'act_c_1',
        approvalId: 'apr_c_1',
        decision: 'rejected',
        resolvedBy: 'user',
      },
      {
        v: 1,
        id: 'evt_c_006',
        ts: '2026-01-01T14:00:20.200Z',
        conversationId: 'conv_cancel',
        type: 'action.failed',
        actionId: 'act_c_1',
        code: 'rejected',
        summary: 'You declined the approval, so the credentials were not rotated.',
        retryable: false,
      },
      {
        v: 1,
        id: 'evt_c_007',
        ts: '2026-01-01T14:00:25.000Z',
        conversationId: 'conv_cancel',
        type: 'conversation.cancelled',
        reason: 'user',
      },
    ],
  },
  delegation: {
    name: 'delegation',
    description:
      'A full delegated action: the user asks, the voice model delegates, the agent reports progress, asks for approval, produces an artifact, and returns a verified result.',
    events: [
      {
        v: 1,
        id: 'evt_d_001',
        ts: '2026-01-01T12:00:00.000Z',
        conversationId: 'conv_delegation',
        type: 'conversation.started',
        agentName: 'agent-voice',
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_d_002',
        ts: '2026-01-01T12:00:01.000Z',
        conversationId: 'conv_delegation',
        type: 'user.transcript.partial',
        segmentId: 'seg_u_1',
        text: 'Can you check whether the nightly',
      },
      {
        v: 1,
        id: 'evt_d_003',
        ts: '2026-01-01T12:00:02.000Z',
        conversationId: 'conv_delegation',
        type: 'user.transcript.final',
        segmentId: 'seg_u_1',
        text: 'Can you check whether the nightly build passed and re-run anything that failed?',
      },
      {
        v: 1,
        id: 'evt_d_004',
        ts: '2026-01-01T12:00:02.400Z',
        conversationId: 'conv_delegation',
        type: 'agent.message.partial',
        messageId: 'msg_a_1',
        text: "Sure, I'll ask the agent",
      },
      {
        v: 1,
        id: 'evt_d_005',
        ts: '2026-01-01T12:00:03.000Z',
        conversationId: 'conv_delegation',
        type: 'agent.message.final',
        messageId: 'msg_a_1',
        text: "Sure, I'll ask the agent to check the nightly build.",
      },
      {
        v: 1,
        id: 'evt_d_006',
        ts: '2026-01-01T12:00:03.200Z',
        conversationId: 'conv_delegation',
        type: 'action.started',
        actionId: 'act_d_1',
        title: 'Check the nightly build and re-run failures',
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_d_007',
        ts: '2026-01-01T12:00:04.500Z',
        conversationId: 'conv_delegation',
        type: 'action.progress',
        actionId: 'act_d_1',
        message: 'Fetching the latest nightly run',
        percent: 20,
      },
      {
        v: 1,
        id: 'evt_d_008',
        ts: '2026-01-01T12:00:06.000Z',
        conversationId: 'conv_delegation',
        type: 'action.progress',
        actionId: 'act_d_1',
        message: 'Two jobs failed: integration-suite and docs-build',
        percent: 55,
      },
      {
        v: 1,
        id: 'evt_d_009',
        ts: '2026-01-01T12:00:06.500Z',
        conversationId: 'conv_delegation',
        type: 'approval.requested',
        actionId: 'act_d_1',
        approvalId: 'apr_d_1',
        prompt: 'Re-run the two failed jobs on the nightly pipeline?',
        expiresAt: '2026-01-01T12:02:06.500Z',
      },
      {
        v: 1,
        id: 'evt_d_010',
        ts: '2026-01-01T12:00:10.000Z',
        conversationId: 'conv_delegation',
        type: 'approval.resolved',
        actionId: 'act_d_1',
        approvalId: 'apr_d_1',
        decision: 'approved',
        resolvedBy: 'user',
      },
      {
        v: 1,
        id: 'evt_d_011',
        ts: '2026-01-01T12:00:12.000Z',
        conversationId: 'conv_delegation',
        type: 'action.progress',
        actionId: 'act_d_1',
        message: 'Re-running integration-suite and docs-build',
        percent: 80,
      },
      {
        v: 1,
        id: 'evt_d_012',
        ts: '2026-01-01T12:00:14.000Z',
        conversationId: 'conv_delegation',
        type: 'artifact.created',
        actionId: 'act_d_1',
        artifact: {
          id: 'art_d_1',
          kind: 'link',
          title: 'Nightly pipeline run #4812',
          url: 'https://ci.example.com/pipelines/4812',
        },
      },
      {
        v: 1,
        id: 'evt_d_013',
        ts: '2026-01-01T12:00:15.000Z',
        conversationId: 'conv_delegation',
        type: 'action.verified',
        actionId: 'act_d_1',
        summary:
          'The nightly build had two failures, integration-suite and docs-build. Both were re-run and are now queued.',
        verification: {
          state: 'verified',
          method: 'agent:tool-check',
          detail: 'Delegated agent checked the resulting pipeline state',
        },
        artifacts: [
          {
            id: 'art_d_2',
            kind: 'text',
            title: 'Failure summary',
            text: 'integration-suite: timeout after 20m\ndocs-build: broken link in docs/api.md',
          },
        ],
      },
      {
        v: 1,
        id: 'evt_d_014',
        ts: '2026-01-01T12:00:15.500Z',
        conversationId: 'conv_delegation',
        type: 'agent.message.partial',
        messageId: 'msg_a_2',
        text: 'The nightly build had two failures',
      },
      {
        v: 1,
        id: 'evt_d_015',
        ts: '2026-01-01T12:00:17.000Z',
        conversationId: 'conv_delegation',
        type: 'agent.message.final',
        messageId: 'msg_a_2',
        text: 'The nightly build had two failures, the integration suite and the docs build. Both have been re-run and are queued now.',
      },
    ],
  },
  failure: {
    name: 'failure',
    description:
      'The delegated agent is unreachable: the action fails honestly and nothing is claimed.',
    events: [
      {
        v: 1,
        id: 'evt_f_001',
        ts: '2026-01-01T13:00:00.000Z',
        conversationId: 'conv_failure',
        type: 'conversation.started',
        agentName: 'agent-voice',
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_f_002',
        ts: '2026-01-01T13:00:02.000Z',
        conversationId: 'conv_failure',
        type: 'user.transcript.final',
        segmentId: 'seg_u_1',
        text: "Archive last month's invoices.",
      },
      {
        v: 1,
        id: 'evt_f_003',
        ts: '2026-01-01T13:00:02.800Z',
        conversationId: 'conv_failure',
        type: 'action.started',
        actionId: 'act_f_1',
        title: "Archive last month's invoices",
        adapter: 'openai-http',
      },
      {
        v: 1,
        id: 'evt_f_004',
        ts: '2026-01-01T13:00:08.000Z',
        conversationId: 'conv_failure',
        type: 'action.failed',
        actionId: 'act_f_1',
        code: 'unavailable',
        summary: 'The agent is not reachable right now, so nothing was changed.',
        retryable: true,
      },
      {
        v: 1,
        id: 'evt_f_005',
        ts: '2026-01-01T13:00:09.000Z',
        conversationId: 'conv_failure',
        type: 'agent.message.final',
        messageId: 'msg_a_1',
        text: "I couldn't reach the agent, so the invoices were not archived. Want me to try again?",
      },
    ],
  },
} as const;
